name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: your-username # Replace with your GitHub username
          output: dist/github-contribution-grid-snake.svg

      # Push the animation to the repository
      - name: Commit and Push
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          keep_files: true
          committer: GitHub <noreply@github.com>
          commit_message: "Generate snake animation"
